services:
  discord-blocked-account-detect-bot:
    container_name: discord-blocked-account-detect-bot
    build: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 30678:30678
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: bridge